# Generated by Django 6.0.3 on 2026-03-17 03:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bateaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('camera', 'Camera'), ('ais', 'AIS'), ('satellite', 'Satellite')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bateaux.boat')),
            ],
        ),
    ]
