# Generated by Django 6.0.3 on 2026-03-17 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0001_initial'),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detection',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bateaux.boat'),
        ),
    ]
