# Generated by Django 6.0.3 on 2026-03-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detection_created_at_alter_detection_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='mmsi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
