# Generated by Django 6.0.3 on 2026-03-18 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0004_remove_boat_size_class_alter_boat_mmsi'),
        ('detection', '0003_detection_mmsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Vitesse actuelle (SOG) envoyée par AISStream'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='bateaux.boat'),
        ),
    ]
