# Generated by Django 6.0.3 on 2026-03-18 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0005_remove_boat_first_seen_boat_last_seen_boat_name_and_more'),
        ('detection', '0004_detection_speed_alter_detection_boat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='confidence',
        ),
        migrations.AlterField(
            model_name='detection',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='bateaux.boat'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='source',
            field=models.CharField(default='ais', max_length=20),
        ),
        migrations.AlterField(
            model_name='detection',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
