# Generated by Django 6.0.3 on 2026-03-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_remove_detection_confidence_alter_detection_boat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='eta_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
