# Generated by Django 6.0.3 on 2026-03-17 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bateaux', '0001_initial'),
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bateaux.boat')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.port')),
            ],
        ),
    ]
