# Generated by Django 6.0.3 on 2026-03-17 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boats_in_port', models.IntegerField()),
                ('entries', models.IntegerField()),
                ('exits', models.IntegerField()),
                ('congestion_level', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.port')),
            ],
        ),
    ]
