# Generated by Django 6.0.3 on 2026-03-17 03:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('confidence', models.FloatField()),
                ('image_source', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
