# Generated by Django 6.0.3 on 2026-03-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(blank=True, max_length=20, null=True)),
                ('size_class', models.CharField(choices=[('small', 'Small Boat'), ('medium', 'Medium Boat'), ('large', 'Large Boat')], max_length=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
