# Generated by Django 6.0.3 on 2026-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='length',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='boat',
            name='tonnage',
            field=models.FloatField(default=50.0),
        ),
    ]
