# Generated by Django 6.0.3 on 2026-03-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0002_boat_length_boat_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='ship_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
