# Generated by Django 6.0.3 on 2026-03-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0003_boat_ship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='size_class',
        ),
        migrations.AlterField(
            model_name='boat',
            name='mmsi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
