# Generated by Django 6.0.3 on 2026-03-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0004_remove_boat_size_class_alter_boat_mmsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='first_seen',
        ),
        migrations.AddField(
            model_name='boat',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='ship_type',
            field=models.IntegerField(default=30),
        ),
    ]
