# Generated by Django 6.0.3 on 2026-03-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bateaux', '0005_remove_boat_first_seen_boat_last_seen_boat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='width',
            field=models.FloatField(default=5.0),
        ),
    ]
