# Generated by Django 6.0.3 on 2026-03-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField()),
                ('confidence', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Boat Traffic',
            },
        ),
    ]
